
name: documentation

on:
  push:
    branches:
      - main
    tags: '*'

env:
  JULIA_PKG_USE_CLI_GIT: true #github runner was not checking out Utility...https://discourse.julialang.org/t/prepare-self-hosted-runner-on-windows-10-for-github-actions-and-julia-private-registry-and-packages/82367
  GKSwstype: 100 # for gr() headless.. https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988/5
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'


      - name: Install Qt
        uses: jurplel/install-qt-action@v2 #220804, v3 broken: https://github.com/jurplel/install-qt-action/issues/153
        with:
          host: 'linux'
          target: 'desktop'

      # - name: Install matplotlib
      #   run: if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get install -y python3-matplotlib; fi
      #   shell: bash

      # # manually checking-out leads to a version conflict with BT's expected versions..?
      # - uses: actions/checkout@v3
      #   with: 
      #     repository: 'mechanomy/Utility.jl'

      # - uses: actions/checkout@v3
      #   with: 
      #     repository: 'mechanomy/Geometry2D.jl'


      - name: Checkout BeltTransmission
        uses: actions/checkout@v2 
        with:
          lfs: true #enable lfs
      - run: git lfs pull #pull the objects (favicon.ico, logo.png) down

      - name: Install dependencies
        env:
          PYTHON: "" #By setting python to null, the PyPlot in docs/Project.toml will install matplotlib itself
        # run: julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools"); Pkg.add("DocStringExtensions"); Pkg.add(url="https://github.com/mechanomy/Utility.jl"); Pkg.add(url="https://github.com/mechanomy/Geometry2D.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        # run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        run: julia --project=docs/ -e 'using Pkg; Pkg.add(url="https://github.com/mechanomy/Utility.jl"); Pkg.add(url="https://github.com/mechanomy/Geometry2D.jl"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      # - name: pre Build and deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
      #     DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
      #   # run: julia --project=docs/ docs/make.jl
      #   run: pwd && ls && tree && julia --project=docs/ -e 'pwd()'

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        # run: julia --project=docs/ docs/make.jl
        run: julia --project=docs/ -e 'pwd()' && julia --project=docs/ docs/make.jl
